# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_projects', '0002_auto_20190228_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroupreview',
            name='submitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
